name: milo_bitcoin
channels:
  - pytorch      # Use official PyTorch channel to ensure GPU version
  - nvidia       # Official NVIDIA channel for CUDA support
  - conda-forge  # source of other packages
  # Note: Exclude defaults channel to avoid version conflicts

dependencies:
  - python=3.10
  
  # PyTorch GPU version (explicitly specify pytorch channel for GPU version)
  - pytorch::pytorch>=2.0.0
  - pytorch::torchvision  
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.1  # Explicit CUDA version
  
  # Basic scientific computing
  - numpy=1.24.*
  - pandas=2.0.*
  - scipy
  - scikit-learn
  
  # Data visualization
  - matplotlib=3.7.*
  - seaborn=0.12.*
  
  # Network and utilities
  - requests=2.31.*
  - tqdm=4.65.*
  - python-dateutil=2.8.*
  - beautifulsoup4>=4.12.0
  - lxml

  # Natural Language Processing
  - nltk

  # FAISS GPU version (more stable through conda installation)
  - faiss-gpu>=1.7.0  # Support available version range
  
  # Development tools
  - jupyter
  - ipykernel
  - git
  
  # pip packages (install after conda installation)
  - pip
  - pip:
    # Core AI/ML packages
    - transformers>=4.35.0
    - peft>=0.7.0
    - sentence-transformers>=2.2.0
    - accelerate>=0.24.0
    - bitsandbytes>=0.41.0
    
    # Unsloth related (separate installation is more reliable)
    - "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
    - unsloth_zoo  # Explicitly include dependencies
    
    # RAG system
    - langchain>=0.1.0
    - langchain-community>=0.0.10
    - chromadb>=0.4.0
    # faiss-gpu installed via conda, not duplicated in pip

    # PDF and document processing
    - PyPDF2>=3.0.0
    - pdfplumber>=0.9.0

    # Text processing and utilities
    - spacy>=3.7.0
    - regex>=2023.0.0
    
    # MCP related
    - anthropic
    - python-dotenv>=1.0.0
    
    # Web frameworks
    - streamlit>=1.28.0
    - gradio>=4.0.0
    - fastapi>=0.104.0
    - uvicorn>=0.24.0
    
    # Enhanced data visualization
    - plotly>=5.17.0
    
    # GPU monitoring tools
    - gpustat
    - py3nvml

    # Additional data processing tools
    - python-multipart>=0.0.6
    - aiofiles>=23.0.0

    # Optional: vLLM for GPT-OSS-20B deployment (install after fine-tuning)
    # - --pre vllm==0.10.1+gptoss

# Post-installation verification script (kept as comments)
# conda activate milo_bitcoin
# python -c "import torch; print(f'CUDA: {torch.cuda.is_available()}')"
# python -c "import unsloth; print('✅ Unsloth success')"
# python -c "import transformers, langchain; print('✅ AI packages success')"